### ISSUE TITLE
refactor: fixtures

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-rdm-records#1145]
The module contains references to create user fixtures, vocabularies, etc. 
The fixture adding mechanism is located in this module, which causes the developers to add fixtures of objects which are not within the scope of this module (f.e. users).
The fixture creation needs to be centralised and extensible, so that they are added only in the respoctive modules, or directly in app-rdm

**Comment by alejandromumo** [comment]
Note: when features are not added, it's not possible to upload a new record:

```
Traceback (most recent call last):
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/decorators.py", line 263, in view
    return f(**kwargs)
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/deposits.py", line 343, in deposit_create
    forms_config=get_form_config(createUrl="/api/records"),
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/deposits.py", line 291, in get_form_config
    vocabularies=VocabulariesOptions().dump(),
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/deposits.py", line 243, in dump
    self.depositable_resource_types()
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/deposits.py", line 160, in depositable_resource_types
    self._vocabularies["resource_type"] = self._resource_types(
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/deposits.py", line 112, in _resource_types
    all_resource_types = vocabulary_service.read_all(
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/invenio_vocabularies/services/service.py", line 174, in read_all
    vocabulary_type = VocabularyType.query.filter_by(id=type).one()
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1522, in one
    return self._only_one_row(
  File "/Users/alejandromumo/.virtualenvs/zenodo-rdm-g3Txli9a/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
```
