### ISSUE TITLE
preview: citation box breaks in preview

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#729]
```
Traceback (most recent call last):
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/werkzeug/middleware/dispatcher.py", line 66, in __call__
    return app(environ, start_response)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask_resources/responses.py", line 40, in inner
    return resource_requestctx.response_handler.make_response(*res, many=many)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/flask_resources/responses.py", line 94, in make_response
    "" if obj_or_list is None else serialize(obj_or_list),
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/invenio_rdm_records/resources/serializers/csl/__init__.py", line 99, in serialize_object
    if callable(self.url_args_retriever)
  File "/Users/ppanero/.virtualenvs/june-late/lib/python3.7/site-packages/invenio_rdm_records/resources/config.py", line 27, in csl_url_args_retriever
    style = resource_requestctx.args.get("style")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ppanero** [comment]
Happening with resource type, take into account **all** fields are optional for preview since a draft might or might not have any value.

```
  File "/Users/ppanero/.virtualenvs/v5/lib/python3.7/site-packages/marshmallow/fields.py", line 1864, in _serialize
    return self._serialize_method(obj)
  File "/Users/ppanero/.virtualenvs/v5/lib/python3.7/site-packages/invenio_rdm_records/resources/serializers/csl/schema.py", line 70, in get_type
    resource_type = obj["metadata"]["resource_type"]
KeyError: 'resource_type'
```
