### ISSUE TITLE
DataCite _log_errors method crashes on invalid credentials

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-rdm-records#879]
When publishing a record and the datacite credentials are not valid the following error is shown in the worker-docker-container:

```
[2022-01-25 16:01:51,633: INFO/MainProcess] Task invenio_rdm_records.services.pids.tasks.register_or_update_pid[dc3f7736-85e5-4c2b-a770-c8f156278fcf] received
[2022-01-25 16:01:51,635: INFO/MainProcess] Task invenio_rdm_records.services.pids.tasks.register_or_update_pid[8a6069ff-b6fc-4a31-a215-e7c68454a3a6] received
[2022-01-25 16:01:51,650: INFO/ForkPoolWorker-8] Registered PID.
[2022-01-25 16:01:51,666: INFO/ForkPoolWorker-1] Task invenio_rdm_records.services.pids.tasks.register_or_update_pid[8a6069ff-b6fc-4a31-a215-e7c68454a3a6] succeeded in 0.02980649983510375s: None
[2022-01-25 16:01:51,843: INFO/ForkPoolWorker-8] POST http://es:9200/vocabularies/_search?version=true [status:200 request:0.174s]
[2022-01-25 16:01:51,919: INFO/ForkPoolWorker-8] POST http://es:9200/vocabularies/_search?version=true [status:200 request:0.068s]
[2022-01-25 16:01:52,173: WARNING/ForkPoolWorker-8] [2022-01-25 16:01:52,172] WARNING in datacite: DataCite provider error when updating DOI for 10.23710/DEV-3se6z-hct44

[2022-01-25 16:01:52,172: WARNING/ForkPoolWorker-8] DataCite provider error when updating DOI for 10.23710/DEV-3se6z-hct44
[2022-01-25 16:01:52,176: ERROR/ForkPoolWorker-8] Task invenio_rdm_records.services.pids.tasks.register_or_update_pid[dc3f7736-85e5-4c2b-a770-c8f156278fcf] raised unexpected: KeyError('source')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/services/pids/providers/datacite.py", line 143, in register
    self.client.api.public_doi(
  File "/usr/local/lib/python3.8/site-packages/datacite/rest_client.py", line 210, in public_doi
    return self.post_doi(data)
  File "/usr/local/lib/python3.8/site-packages/datacite/rest_client.py", line 122, in post_doi
    raise DataCiteError.factory(resp.status_code, resp.text)
datacite.errors.DataCiteNotFoundError: {"errors":[{"status":"404","title":"The resource you are looking for doesn't exist."}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_celeryext/app.py", line 84, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/services/pids/tasks.py", line 19, in register_or_update_pid
    current_rdm_records.records_service.pids.register_or_update(
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 292, in inner
    res = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/services/pids/service.py", line 116, in register_or_update
    self._manager.register(
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/services/pids/manager.py", line 217, in register
    provider.register(pid, record=record, url=url)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/services/pids/providers/datacite.py", line 149, in register
    self._log_errors(e)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/services/pids/providers/datacite.py", line 116, in _log_errors
    field = error["source"]
KeyError: 'source'
```

https://github.com/inveniosoftware/invenio-rdm-records/blob/1ac7ae55fc5ba26c3a60bab0646a0e06fb8f6cf9/invenio_rdm_records/services/pids/providers/datacite.py#L116

**Comment by tmorrell** [comment]
Fixed by https://github.com/inveniosoftware/invenio-rdm-records/pull/1315
